import operator
from typing import Annotated, List, TypedDict
from pydantic import BaseModel, Field

# --- Exercise 1: Define Agent State ---
# Goal: Define the state object that will be passed between nodes in the graph.
# It should contain:
# 1. topic: The research topic (str)
# 2. sub_queries: List of search queries generated by the planner (List[str])
# 3. search_results: Accumulated search results (List[str], using operator.add reducer)
# 4. summary: The final generated report (str)
# 5. iteration: To track how many research loops we've done (int)

class ResearchState(TypedDict):
    topic: str
    sub_queries: List[str]
    # annotated means: when a node returns 'search_results', add it to the existing list
    search_results: Annotated[list, operator.add] 
    summary: str
    iteration: int


# We also define the structure for the Planner's output using Pydantic
class ResearchPlan(BaseModel):
    items: list[str] = Field(description="List of 3 distinct research queries to gather information")
